package:
  name: ros-noetic-navigation
  version: 1.17.1
source:
  git_url: https://github.com/ros-gbp/navigation-release.git
  git_rev: release/noetic/navigation/1.17.1-1
  folder: ros-noetic-navigation/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 4
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - cmake
  host:
    - python
    - ros-distro-mutex 0.1 noetic
    - ros-noetic-catkin
  run:
    - python
    - ros-distro-mutex 0.1 noetic
    - ros-noetic-amcl
    - ros-noetic-base-local-planner
    - ros-noetic-carrot-planner
    - ros-noetic-clear-costmap-recovery
    - ros-noetic-costmap-2d
    - ros-noetic-dwa-local-planner
    - ros-noetic-fake-localization
    - ros-noetic-global-planner
    - ros-noetic-map-server
    - ros-noetic-move-base
    - ros-noetic-move-base-msgs
    - ros-noetic-move-slow-and-clear
    - ros-noetic-nav-core
    - ros-noetic-navfn
    - ros-noetic-rotate-recovery
    - ros-noetic-voxel-grid
