package:
  name: ros-noetic-move-slow-and-clear
  version: 1.17.1
source:
  git_url: https://github.com/ros-gbp/navigation-release.git
  git_rev: release/noetic/move_slow_and_clear/1.17.1-1
  folder: ros-noetic-move-slow-and-clear/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 4
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - cmake
  host:
    - python
    - ros-distro-mutex 0.1 noetic
    - ros-noetic-catkin
    - ros-noetic-cmake-modules
    - ros-noetic-costmap-2d
    - ros-noetic-geometry-msgs
    - ros-noetic-nav-core
    - ros-noetic-pluginlib
    - ros-noetic-roscpp
  run:
    - python
    - ros-distro-mutex 0.1 noetic
    - ros-noetic-costmap-2d
    - ros-noetic-geometry-msgs
    - ros-noetic-nav-core
    - ros-noetic-pluginlib
    - ros-noetic-roscpp
